### ISSUE TITLE
Bug introduced by a new lib

### ISSUE THREAD

**Issue by Dum4G** [dmulloy2/ProtocolLib#1057]
**Describe the bug**
Lib doesn't initialize on Arclight 1.16.4-1.0.11-SNAPSHOT-feb567a

**Version Info**
#492 (commit: 30fe81d) 

**Additional context**
[LOGS](https://gist.github.com/Dum4G/4bc6736b135326f4de637f96c509ec72
)

**Comment by Dum4G** [comment]
Yeah, #483 works fine to me and is 3 times smaller in size

**Comment by dmulloy2** [comment]
@PimvanderLoos is there any reason bytebuddy would break compatibility with forge?

**Comment by PimvanderLoos** [comment]
I am not at all familiar with Forge or Arclight (never heard of it before), so I wouldn't really know what's different here off the top of my head. I'll have to take a closer look first. I'll let you know when I find something.

**Comment by PimvanderLoos** [comment]
I tried to run ProtocolLib on [Mohist](https://github.com/Mohist-Community/Mohist) and [CatServer](https://github.com/Luohuayu/CatServer) (the [biggest](https://bstats.org/global/bukkit#serverSoftware) two Forge/Spigot hybrid servers) and it was able to load the plugin just fine on both 1.12 (Mohist/CatServer) and 1.16 (Mohist, did not try CatServer; it looks like it's even less stable than Mohist on 1.16). I was able to join the server and use a simple test plugin (changing falling sand packets to falling dirt packets) on 1.12, but not 1.16 (though it does not appear to be related to the issue described above). However, Mohist doesn't really work for the Spigot part of 1.16 yet (as also noted in their readme, and I was unable to load other plugins (e.g. Essentials) either), so that makes it a bit more difficult to compare two different 1.16.4 Forge hybrid platforms. 

Nonetheless, considering it worked just fine on both Mohist and CatServer on 1.12 and did not cause the same issue on start for 1.16, I think that the issue is likely to be specific to Arclight and not Forge.

**Comment by PimvanderLoos** [comment]
I'm pretty sure that the issue comes from the fact that Arclight hijacks calls to `defineClass` so it can remap stuff. It then fails when analyzing the class [here](https://github.com/IzzelAliz/Arclight/blob/feb567a1933dced276ae483b6febebbc7ad7a637/arclight-common/src/main/java/io/izzel/arclight/common/mod/util/remapper/ArclightInterfaceInvokerGen.java#L75) while checking if any of the class's parents are in the NMS package using their [PluginInheritanceProvider](https://github.com/IzzelAliz/Arclight/blob/9c359490aa7a299f3a7c3d0347732f218f4ac3a5/arclight-common/src/main/java/io/izzel/arclight/common/mod/util/remapper/PluginInheritanceProvider.java) implementation of md_5's [InheritanceProvider](https://github.com/md-5/SpecialSource/blob/master/src/main/java/net/md_5/specialsource/provider/InheritanceProvider.java) because it cannot find the ClassNode from the Class's name and [returns null](https://github.com/IzzelAliz/Arclight/blob/9c359490aa7a299f3a7c3d0347732f218f4ac3a5/arclight-common/src/main/java/io/izzel/arclight/common/mod/util/remapper/PluginInheritanceProvider.java#L26) instead of an empty collection or a descriptive error or something. I don't know why it cannot obtain the ClassNode from the `classRepo`, but I don't have time to look into that right now.

Changing the [ClassLoadingStrategy](https://javadoc.io/static/net.bytebuddy/byte-buddy/1.10.2/net/bytebuddy/dynamic/loading/ClassLoadingStrategy.html) used [here](https://github.com/dmulloy2/ProtocolLib/blob/30fe81d3661121d3f83aeb0afc2fa1a0333bca6c/src/main/java/com/comphenix/protocol/injector/server/TemporaryPlayerFactory.java#L187) from [Default.INJECTION](https://javadoc.io/static/net.bytebuddy/byte-buddy/1.10.2/net/bytebuddy/dynamic/loading/ClassLoadingStrategy.Default.html#INJECTION) to [ForUnsafeInjection](https://javadoc.io/static/net.bytebuddy/byte-buddy/1.10.2/net/bytebuddy/dynamic/loading/ClassLoadingStrategy.ForUnsafeInjection.html) solves this issue (both launching the server + creating temporary players works fine). I haven't looked at the code, but I assume that this works because Arclight is unable to intercept the class defining process this way. However, this requires the usage of Unsafe, which might not be ideal, so fixing it on Arclight's end might be preferable.

**Comment by Dum4G** [comment]
Fixed on Arclight side
