### ISSUE TITLE
The dev build site isn't working.

### ISSUE THREAD

**Issue by JustBeast07** [dmulloy2/ProtocolLib#1087]
The Dev site, Isn't working, So i can't download the 1.16.4 version.

Please fix it!

**Comment by hetile1** [comment]
+1

`Service Unavailable
The server is temporarily unable to service your request due to maintenance downtime or capacity problems. Please try again later.

Additionally, a 503 Service Unavailable error was encountered while trying to use an ErrorDocument to handle the request.

Apache/2.4.25 (Win32) OpenSSL/1.0.2j PHP/5.6.30 Server at ci.dmulloy2.net Port 443`
