### ISSUE TITLE
Packetwrapper messed up after update

### ISSUE THREAD

**Issue by rcth** [dmulloy2/ProtocolLib#111]
Probably not a bug, but it's an issue for me as I can't seem to update my code:
http://prntscr.com/87yodd

Everything worked fine at first. But I had updated the plugin to 1.8.8 and also PacketWrapper and ProtocolLib.

However... Certain methods have been changed, so my code is invalid now.
* I can't simply get the line on a sign now with doing sign.getLines()[0] as before. It's no longer a String, but a WrappedChatComponent[]. How can I convert that to a String for example for the first line (so 0).
* Location has been changed to BlockPosition. How can I convert that to Location again for the blockchange?

Thanks in advance.

EDIT:
com.comphenix.packetwrapper.BlockChangeArray
is missing now too. I need this for the multiblockchange.
http://prntscr.com/87z716

**Comment by dmulloy2** [comment]
These changes happened because of changes in 1.8. You can find equivalent methods in the [javadoc](http://ci.shadowvolt.com/job/PacketWrapper/javadoc/). Basically strings on signs were replaced with chat components (you can get raw JSON with WrappedChatComponent#getJSON(), coordinates were replaced by block positions, and block changes were rewritten for some reason.

**Comment by rcth** [comment]
Sorry for the late reply, but how can I use the JSON from WrappedChatComponent in my String? What's the format?

**Comment by Rocknest** [comment]
WrappedChatComponent -> ComponentConverter.fromWrapper() -> BaseComponent[] -> BaseComponent.toPlainText()/toLegacyText() -> String
