### ISSUE TITLE
Loaded Class {0} from {1} which is not a depend, soft depend or loadbefore of this plugin.

### ISSUE THREAD

**Issue by TheSoraMan** [dmulloy2/ProtocolLib#1116]
**Describe the bug**
I don't know if this classifies as a bug, but it shows OP'd Members this and I don't know how to fix it.

**To Reproduce**
1. Install a Plugin that needs ProtocolLib to work, in my case PosePlugin
2. /lay or /sit then stand up using [shift key]
3. see the prompt

**Expected behavior**
There will be a prompt that says "[ProtocolLib] Loaded Class {0} from {1} which is not a depend, soft depend or loadbefore of this plugin.

**Screenshots**
https://prnt.sc/10isrs8

**Version Info**
ProtocolLib version 4.6.0
https://pastebin.com/5WLYkF2Q

**Additional context**
I don't know if there's more plugins that makes it show that text.

**Comment by LeonMangler** [comment]
I've had the same issue with my plugin PremiumVanish. In my case it only appeared when I was listening to the GAME_STATE_CHANGE packet type and it doesn't appear when I'm only listening to e.g. PLAYER_INFO, ABILITIES and ENTITY_METADATA.
Here's a [ProtocolLib dump](https://pastebin.com/2XYa6Tcq) with the bug in action.

**Comment by Probactrosaurus** [comment]
Have the same Problem with my own Plugin where I use ProtocolLib to edit NBT-Data.
Error in cosole:
`[Server thread/WARN]: [ProtocolLib] Loaded class com.comphenix.protocol.reflect.StructureModifier from Speedrun v1.0 which is not a depend, softdepend or loadbefore of this plugin.`
Happens when new NBT-Data is applied to an item.

**Comment by dmulloy2** [comment]
That message would imply that Speedrun is including ProtocolLib classes in its jar, which it shouldn't be doing

**Comment by LeonMangler** [comment]
I should have included the message I get in the console:
`[00:08:06] [Server thread/WARN]: [ProtocolLib] Loaded class de.myzelyam.premiumvanish.bukkit.features.SilentOpenChestPacketAdapter from PremiumVanish v2.6.11 which is not a depend, softdepend or loadbefore of this plugin.`
It appears that ProtocolLib loaded the class that contains the GAME_STATE_CHANGE packet adapter. I'm not including ProtocolLib in my plugin jar.

**Comment by JasonHorkles** [comment]
This still happens on build 522 so not sure why this was closed, unless it'll be fixed in the future

**Comment by DomiRusz24** [comment]
**Warning: I absolutely have no clue how this plugin works, but from the looks of it, it changes just changes the fields.**
It may be due to the absence of an Integer as the `reason` in the packet `GAME_STATE_CHANGE`. 
Instead, there is a `PacketPlayOutGameStateChange.a` field. There are 11 static instances for this class (corresponding to the 11 reasons), that are located in `PacketPlayOutGameStateChange`. wiki.vg and PacketWrapper both state that it's just an `int`.
![image](https://user-images.githubusercontent.com/46862541/123549350-f14f2a80-d768-11eb-9266-c6c1f45356b5.png)
When trying to use this Packet, I get this error:
`com.comphenix.protocol.reflect.FieldAccessException: No field with type int exists in class PacketPlayOutGameStateChange.`
And in the game, I get the exact message that this issue is about.

**Comment by PrinceBunBun981** [comment]
> **Warning: I absolutely have no clue how this plugin works, but from the looks of it, it changes just changes the fields.**
> (Using 1.16.5)
> It may be due to the absence of an Integer as the `reason` in the packet `GAME_STATE_CHANGE`.
> Instead, there is a `PacketPlayOutGameStateChange.a` field. There are 11 static instances for this class (corresponding to the 11 reasons), that are located in `PacketPlayOutGameStateChange`. wiki.vg and PacketWrapper both state that it's just an `int`.
> ![image](https://user-images.githubusercontent.com/46862541/123549350-f14f2a80-d768-11eb-9266-c6c1f45356b5.png)
> When trying to use this Packet, I get this error:
> `com.comphenix.protocol.reflect.FieldAccessException: No field with type int exists in class PacketPlayOutGameStateChange.`
> And in the game, I get the exact message that this issue is about.

I'm getting the same error in the console when using this:
```
PacketContainer packet = new PacketContainer(PacketType.Play.Server.GAME_STATE_CHANGE);
packet.getInteger().write(0, 4);
packet.getFloat().write(0, 1F);
```
And I've tried changing `packet.getInteger().write(0, 4);` to be a `byte` as well and get the same sort of error.

I've got 0 clue why Spigot changed this, but I remember it being marked as solved or whatever or something being added in ProtocolLib to allow for this, but it seems to not be working even with the latest dev build.

**Comment by dmulloy2** [comment]
@DomiRusz24 @PrinceBunBun981 those look like different issues to this one

**Comment by PrinceBunBun981** [comment]
> @DomiRusz24 @PrinceBunBun981 those look like different issues to this one

Deleted my bad.

**Comment by DomiRusz24** [comment]
> @DomiRusz24 @PrinceBunBun981 those look like different issues to this one

I got the same exact message with this error, thought it's related to eachother.

**Comment by derklaro** [comment]
This message is not send by ProtocolLib but by the spigot plugin class loading stuff. In most cases this indicates that some plugin is shading a class which would normally be provided in runtime by spigot anyway, but given how the class loading in spigot works the other plugin loader is called first leading to the given message (seems like how the message is sent is invalid, therefore the information which should be available through {0} and {1} is not properly replaced).

See: https://hub.spigotmc.org/stash/projects/SPIGOT/repos/bukkit/browse/src/main/java/org/bukkit/plugin/java/PluginClassLoader.java#135
