### ISSUE TITLE
PlayerDataInfo Compilation -  very high cpu load

### ISSUE THREAD

**Issue by themazim** [dmulloy2/ProtocolLib#124]
I am not quite sure if it's a bug or necessary due to the packets nature.

Player Data Info packets (Nicknamer, with skin change) are compiled on every occurence. Adding lots of load to the server with arround a hundred player every 30 seconds.

For now running an async thread for reading, editing and sending the packets is using a full core (4,4 ghz): 

http://puu.sh/kYqol/f2fc5082b6.png

if it's handled syncronously the server is having lags and even without editing (just reading) the packet the high cpu load is occuring.

Is it possible to cache the packet / Structure , like it's already done in other cases?

I did some profiling, ~70% (8000 out of 11000) of cpu time is used for 
loader.loadClass(PACKAGE_NAME.replace('/', '.') + "." + className);

in 

https://github.com/dmulloy2/ProtocolLib/blob/master/ProtocolLib/src/main/java/com/comphenix/protocol/reflect/compiler/StructureCompiler.java method lookupClassLoader

**Comment by dmulloy2** [comment]
Ironically it looks like the issue is with the caching. I haven't really delved into the background compilation code (always assumed it just kinda worked), but it looks like that method is called from the background compiler here: https://github.com/dmulloy2/ProtocolLib/blob/master/ProtocolLib/src/main/java/com/comphenix/protocol/reflect/compiler/BackgroundCompiler.java#L250

It looks like it's checking if the class has already been cached, but that way must not scale particularly well.

I'll look into it further when I get the chance.

**Comment by dmulloy2** [comment]
In the meantime, you could try disabling background compilation all together and see if that helps/

**Comment by themazim** [comment]
Disabling cloadClass resolved the issue. No more high CPU load.

http://puu.sh/l5sZp/a07d0108c5.png
