### ISSUE TITLE
JavaDoc search button

### ISSUE THREAD

**Issue by Inxity** [dmulloy2/ProtocolLib#1334]
**Describe the bug**
Javadoc search button not working, website says "JavaScript is disabled on your browser." even its enabled i tried different browsers too like edge, chrome, firefox and opera

**To Reproduce**
Goto https://ci.dmulloy2.net/job/ProtocolLib/javadoc/index.html
try using search button

**Expected behavior**
Search button should work

**Screenshots**
nop

**Version Info**
nop website bug

**Additional context**
nopp

**Comment by dmulloy2** [comment]
Seems to be related to security settings in Jenkins: https://stackoverflow.com/questions/35018767/because-the-documents-frame-is-sandboxed-and-the-allow-scripts-permission-is

I'll see what I can do, but it may just not work. If you go to the tree view (https://ci.dmulloy2.net/job/ProtocolLib/javadoc/), you can at least CTRL+F class names

**Comment by AgainPsychoX** [comment]
Still no progress on this?

**Comment by zax71** [comment]
I am getting the same issue, just it is preminiantly there not just when searching so the JavaDoc isn't of much use to me. Is there an alterniative way of brousing documentation?

Image: [https://sxcu.net/5rTvP49HN](https://sxcu.net/5rTvP49HN)

**Comment by qualk** [comment]
It still doesn't work, says the same message
