### ISSUE TITLE
Handshake Protocol

### ISSUE THREAD

**Issue by SkyBeastMC** [dmulloy2/ProtocolLib#140]
Hello, I'm creating plugins with your software, but I found a but on the lastest recommended (uploaded in DevBukkit) version.

My code work in the 3.4.0 (for 1.7.10-) version of this plugin, but in the new 3.6.4 version, it seems like that doesn't work :/

'event.getPacket().getProtocols().read(0)' doesn't work.

I've tested with getStrings, getIntegers (like the official wiki), anyway to make it working.

Paste: http://pastebin.com/ZVU2wX4L

Could you, please, fix it ? I work with the 1.7.10protocolhack spigot version, and I need to get protocols to see clients' version and send title, tab header and footer packets for 1.8 users only. (That's why I need the 1.8-minecraft version of this plugin for my 1.7 server :) )

**Comment by dmulloy2** [comment]
I gotta say I'm disappointed people are still using the protocol hack. 

As I understand it (although it's been over a year since I used it), the protocol hack is 1.7.10 code that supports 1.8 clients by 'hacking' or modifying the packet inputs and outputs when sending.

But in order to do what you want, you should use ProtocolManager#getVersion(Player) to get their protocol version, not packets.

**Comment by SkyBeastMC** [comment]
Yeah, but hmm 1.7 pvp rules ? Some players (in France, i'm french) are
searching 1.7 servers for PVP.
Also, thanks a lot, I didn't knew that there is a getVersion method!

2016-01-21 1:55 GMT+01:00 Dan Mulloy <notifications@github.com>:
