### ISSUE TITLE
Encountered a LinkageError (likely a misbehaving wrapper)

### ISSUE THREAD

**Issue by gomeylor** [dmulloy2/ProtocolLib#1434]
[dump-2021-11-10_15.43.50.txt](https://github.com/dmulloy2/ProtocolLib/files/7514015/dump-2021-11-10_15.43.50.txt)

Good time of day. I noticed that sometimes after restarting my server, this ProtocolLib error appears because of which players cannot log in to the server as well, after I restart the server again, this error disappears

server version: paperspigot 1.12.2
java: 8

error: https://pastebin.com/vY9dQynU

**Comment by dmulloy2** [comment]
That's really odd. It's hard to say too much meaningful, other than that it seems to be happening on chunk packets. Which is also strange because I don't see any chunk/map chunk listeners in the dump.

Give the debugging steps here a try: https://github.com/dmulloy2/ProtocolLib/wiki/Common-Errors#plugins

Odds are it's some plugin doing something naughty
