### ISSUE TITLE
Protoclib - high usage

### ISSUE THREAD

**Issue by Aides123** [dmulloy2/ProtocolLib#1505]
**Describe the bug**
According to SPARK, the protoclib plugin generates a large load
https://spark.lucko.me/g5xTRiVcVn
**Expected behavior**
XXX

**Version Info**
https://pastebin.com/urKYENRX

**Comment by derklaro** [comment]
Can you explain this in more detail please? I'm not 100% sure how to interpret your spark report correctly, from just looking at the sources view, ProtcolLib is only using ~8% of the server load and this is mostly caused by the native netty channel writes which are required (and would get done by the server anyways)...

Am I just interpreting the report wrong there?
