### ISSUE TITLE
World Border bug

### ISSUE THREAD

**Issue by XenonsEU** [dmulloy2/ProtocolLib#1506]
**Describe the bug**
All options related to world border seem to work other than world border size
managed to deduce this when setting world border to center 0 0 and any size
teleporting to 0.00 0.00 exactly, there is not border warning but as soon as player moves at all it appears 

**To Reproduce**
Setting all world border options to any parameters should work as expected except the world border size which does not seem to make any difference

**Expected behavior**
World border size should be as set and not 0

**Screenshots**
-

**Version Info**
protocol lib 540 on 1.18.1 latest papermc

**Additional context**
Sadly I might not be of too much help since I used protocol lib through skript but I had a friend attempt the same process with java and same result occurred

**Comment by derklaro** [comment]
Honestly this does not sound like a ProtocolLib issue to me (at least based on your explaination). This issue is either caused by
 * you not sending the correct data to the client
 * the client misbehaving in that case
 
ProtocolLib will only modify / create the packet sent to the client and not the way how the client handles the received data...

**Comment by dmulloy2** [comment]
Additionally it's going to be pretty hard to debug with the added complexity of skript
