### ISSUE TITLE
How to check played sound

### ISSUE THREAD

**Issue by darksider1010** [dmulloy2/ProtocolLib#1525]
**Describe the question**
Is it possible check the current played sound? (Clientside)

**API method(s) used**
Nothing

**Expected behavior**
The player should collect all Minecraft sounds. After each sound, he gets a reward.

**Code**
Nothing

**Comment by derklaro** [comment]
Hey, 

First of all this is an issue tracker for protocol lib, if you have questions regarding the minecraft protocol I recommend using https://wiki.vg or their linked discord server.

Anyways, the server has 3 main packets which get send to the client in order to play a sound: 
 * Sound Effect (0x5D)
 * Named Sound Effect (0x19)
 * Entity Sound Effect (0x5C)
 
These 3 are the sound effects which you can get by hooking into the player pipeline. However some sound (like ambient ones) are played based on the client environment without any impact from the server side. I don't have a list of them and would suggest looking into the client source to see which sounds are played based a server command and which sounds 
are played by the client.
