### ISSUE TITLE
ProtocolLib and CatServer

### ISSUE THREAD

**Issue by BurnhamR** [dmulloy2/ProtocolLib#1558]
**Describe the bug**
ProtocolLib and CatServer commonly has issues that don't occur on normal Spigot or Paper.

**To Reproduce**
Setup CatServer.
Install a plugin like Premium Vanish
Install ProtocolLib
Run the server
Join the server(May have to join and leave a few times)
Error displays

Depending on the plugin, you may have to run a command or a different action.

**Expected behavior**
No Errors and plugins to work properly.

**Examples Of Errors**
https://pastebin.com/NQqfksu7
https://pastebin.com/u9RjpFFc
https://pastebin.com/NwBfmTPa
https://pastebin.com/zgVqfkcW

**Version Info**
https://pastebin.com/gFu3Tt1E

**Comment by derklaro** [comment]
> that don't occur on normal Spigot or Paper

Thats due to the fact that spigot, paper etc. are supported, while all types of "hybrid bukkit" server implementations are not. Just use a proper Spigot fork and everything will work fine :)

**Comment by BurnhamR** [comment]
It would be amazing to see more "hybrid bukkit" server implementations supported with protocol lib, as its a dependency of many other plugins that do support CatServer and others.

**Comment by derklaro** [comment]
For normal plugins this is not a problem because the bukkit api works as intended, however ProtocolLib is fiddling **A LOT** with internals of the server which chnanges from hybrid fork to hybrid fork, which just makes it even harder to correctly update to new versions of minecraft. If we try to support each implementation, this will result in a huge mess...
