### ISSUE TITLE
Plugin incompatibility massive spam error?[1.17.1]

### ISSUE THREAD

**Issue by illudota** [dmulloy2/ProtocolLib#1583]
**Describe the bug**
Hello I have this plugin called Printer, Dev tried so much fixing this but for some reason he just can't fix it, ProtocolLib spams with this plugin, and most of the lines are from protocollib.

**To Reproduce**
1. Install Printer Plugin https://www.spigotmc.org/resources/printer.79811/
2. Install ProtoclLib
3. Actually get players in your server and at some point this error will spam
Try to make sure server is 1.17.1 too?

**Expected behavior**
Error spam on console

**Screenshots**
I dont have but i have lines of error:
https://pastebin.com/LMW2A3r2

**Version Info**
https://pastebin.com/2bA7ufXU
I have provided this when i already removed printer plugin.
its both ways actually, if i remove printer plugin no more error, if i remove protocollib no more error, but i just remove printer since i need protocollib better, but I hope the incompat gets fixed.

**Additional context**
None

**Comment by ItzHexGamerYT** [comment]
yes it is true but not only with that plugin, an error also appears if the plugin is alone..
it's a bug of the plugin as it massively spams the console all the time

**Comment by illudota** [comment]
> yes it is true but not only with that plugin, an error also appears if the plugin is alone.. it's a bug of the plugin as it massively spams the console all the time

damn I hope they fix it

**Comment by ItzHexGamerYT** [comment]
I found a solution: use the plugin in an older stable version (if it's a current 1.18 server, I don't recommend it much, but it's the stable version of the plugin) ProtocolLib v3.6.4+

you can download it on spigot:
https://www.spigotmc.org/resources/protocollib.1997/history

**Comment by derklaro** [comment]
Hi,
the problem is (maybe that helps the developer) that the packet event is called asynchronously when receiving the packet (from the netty event loop, during decoding) which is an expected behaviour. However, spigot catches async access to the level entites which is the error you see. There is currently a pull request pending which improves that behaviour (#1566) but is still in work as it only works for 1.18 servers. 

I don't know what the printer plugin is trying to do at that point, but I hope this input helps to fix the issue.
