### ISSUE TITLE
1.19.3 error when trying to join server

### ISSUE THREAD

**Issue by Michael-A-Sloan** [dmulloy2/ProtocolLib#2025]
- [x] This issue is not solved in a development build

**Describe the bug**
Found that when trying to join my server and others trying to join I get this error.
when running in papers most updated 1.19.3
https://pastebin.com/BGnqhCJY

newest one found:
https://pastebin.com/SdLJ67di

It doesn't allow players to join the server at all.

**To Reproduce**
1. Get on Minecraft try to join the server.
2. Wait and see that it didn't let you join.

**Expected behavior**
to be able to join the server and others to join.

**Version Info**
Provide your ProtocolLib install info with `/protocol dump` through pastebin.

https://pastebin.com/MejZLpjG

**Comment by Michael-A-Sloan** [comment]
also got this 

Internal Exception: io.netty.handler.codec.EncoderException: java.lang.ClassCastException: class net.minecraft.network.syncher.DataWatcher$Item cannot be cast to class net.minecraft.network.syncher.DataWatcher$b (net.minecraft.network.syncher.DataWatcher$Item and net.minecraft.network.syncher.DataWatcher$b are in unnamed module of loader java.net.URLClassLoader @5c29bfd)

**Comment by Michael-A-Sloan** [comment]
nope this is probably an issue with 1.19.3 update for them
we are waiting on the to update atm.

**Comment by lukalt** [comment]
This problem is caused if you are using a plugin that has not been updated (properly) to the most recent ProtocolLib version yet. 
Apparently, metadata values are no longer stored in a list of WrappedWatchableObjects (DataWatcher$Item) but rather in a list of WrappedDataValues (DataWatcher$b). 

Here you can find a way to update this: https://pastebin.com/EuprZGHe

**Comment by lokka30** [comment]
Linked to #2032
