### ISSUE TITLE
Packet encoding of packet ID 78 threw (skippable? false)

### ISSUE THREAD

**Issue by aaa8881** [dmulloy2/ProtocolLib#2392]
- [x] This issue is not solved in a development build

**Describe the bug**
https://pastebin.com/CT9sPm4T

1. players sometimes get kick out when breaking shulker box
2. all players around shulker box get affected
3. anything from https://github.com/dmulloy2/ProtocolLib/issues/2094 doesn't help. 
4. has been issue for 3 months , happened in protocolLib build616 , and still happens in build639

**To Reproduce**
unsure not definite.

**Version Info**
https://pastebin.com/eiiWtB9r

**Additional context**
pufferfish-61 ( paper 1.19.3 fork )

**Comment by lukalt** [comment]
Why do you assume that this is caused by ProtocolLib?

**Comment by lukalt** [comment]
I've checked out the exact build you are using and it seems like a bug in the fastutil library. It seems like the internal counter for the map size and the number of actual elements get out of sync leading to a negative map size. I do not see how this can be caused by ProtocolLib. Maybe some of you plugins modifies the NBT data via ProtocolLib but the bug itself is in fastutil.

I would suggest you to create an issue at https://github.com/PaperMC/Paper/issues so they can either update the library or submit an issue there.

**Comment by aaa8881** [comment]
> I've checked out the exact build you are using and it seems like a bug in the fastutil library. It seems like the internal counter for the map size and the number of actual elements get out of sync leading to a negative map size. I do not see how this can be caused by ProtocolLib. Maybe some of you plugins modifies the NBT data via ProtocolLib but the bug itself is in fastutil.
> 
> I would suggest you to create an issue at https://github.com/PaperMC/Paper/issues so they can either update the library or submit an issue to the fastutil project.

Hi, after you commented, I tried removing all plugins that I could find in the stack trace

https://pastebin.com/kvVV9DkA

and it still happens unfortunately. I posted in protcolLib because I see protocolLib in the stack trace at the very beginning. that's all

If this is flaw of using wrong fastUtil from bukkit ( using pufferfish#61 ) , would you believe this is technically unresolveable without changing internal code of bukkit?

**Comment by lukalt** [comment]
Thank you for the follow up. I still cannot think how this can be caused by ProtocolLib. One thing I can imagine is that some other plugin (probably LibsDisguises) asynchronously modifies this map leading to a data race. However, this is nothing ProtocolLib can take care of. I really suggest you, to submit the bug to Paper.

**Comment by aaa8881** [comment]
Thanks for reply, lukalt.

After some investigation, we found that many players actually knew how to prevent this from happening interestingly, and found out this is definitely related to some client sides modes. 

Almost every player who initiated this problem has inventory related client mode such as ``inventory tweak`` , ``mouse tweak`` or ``IPN`` .
what they have in common is, those client side mods move items around with non-vanilla way. such as sorting inventory , quickly putting items into sort and so on. 

not really sure if I could do something about it, but I guess I needa discuss this with paper.
