### ISSUE TITLE
playerdata send packet

### ISSUE THREAD

**Issue by dinobossytnew** [dmulloy2/ProtocolLib#2610]
https://bin.bloom.host/upelaluquc.properties

**Comment by Dymeth** [comment]
Provide more info using this form: 

- [ ] This issue is not solved in a development build

**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Version Info**
Provide your ProtocolLib install info with `/protocol dump` through pastebin.

**Additional context**
Add any other context about the problem here.

**Comment by BijuuKrunos** [comment]
Have the same error, here some datas:

**Describe the bug**
Sometimes if a player is changing the Server in my Network it get kicked with the error Message from above.

**To Reproduce**
Change from one Server to another inside a Bungeecord Network, if your unlucky, you get kicked with the error message.

**Expected behavior**
Not get kicked...

**Screenshots**
![image](https://github.com/dmulloy2/ProtocolLib/assets/38471938/98393f14-bca6-4532-b5ff-bd50eeff7f45)

**Version Info**
https://pastebin.com/RKsBAdwg


Hope this helps to get this solved quickly.

**Comment by Dymeth** [comment]
> Have the same error, here some datas:
> 
> **Describe the bug** Sometimes if a player is changing the Server in my Network it get kicked with the error Message from above.
> 
> **To Reproduce** Change from one Server to another inside a Bungeecord Network, if your unlucky, you get kicked with the error message.
> 
> **Expected behavior** Not get kicked...
> 
> **Screenshots** ![image](https://user-images.githubusercontent.com/38471938/284068725-98393f14-bca6-4532-b5ff-bd50eeff7f45.png)
> 
> **Version Info** https://pastebin.com/RKsBAdwg
> 
> Hope this helps to get this solved quickly.

Try to use dev build of ProtocolLib v5.1.1 from here:
[1.8-1.19.4]: https://ci.dmulloy2.net/job/
[1.20.*+]: https://ci.dmulloy2.net/job/ProtocolLib/669/

Notice for 1.20 and 1.20.1 users:
Please, use 1.20.2 to confirm your issue with ProtocolLib.

Why not the last build for 1.20.2?
Last build (673) have critical issue at this moment; https://github.com/dmulloy2/ProtocolLib/issues/2601

If the problem persists, provide more information about your problem using this form:

- [ ] This issue is not solved in a development build

**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Version Info**
Provide your ProtocolLib install info with `/protocol dump` through pastebin.

**Additional context**
Add any other context about the problem here.

**Comment by BijuuKrunos** [comment]
We have some more Problems with 1.20.2 thats why we are not updating currently.
I changed the Protocollib Version back to 699.
The Problem on Testing is that this issue is rare, even after 30 switched i could not get it again.
I now will see if in the next days this issue is comming again with the 699 Version.
