### ISSUE TITLE
have errors with using version 5.1.0

### ISSUE THREAD

**Issue by SexyLemonz** [dmulloy2/ProtocolLib#2628]
- [ ] This issue is not solved in a development build

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Version Info**
Provide your ProtocolLib install info with `/protocol dump` through pastebin.

**Additional context**
[07:05:48] [Server thread/INFO]: [ProtocolLib] Loading server plugin ProtocolLib v5.1.0
[07:05:48] [Server thread/WARN]: [ProtocolLib] Version (MC: 1.20.2) has not yet been tested! Proceed with caution.
[07:05:48] [Server thread/ERROR]: [ProtocolLib] INTERNAL ERROR: Cannot load ProtocolLib.
If this problem hasn't already been reported, please open a ticket

i tried the dev build 673 released on oct 25th and it just makes it where it says incomp version of the game and wont let me join the server.

**Comment by Dymeth** [comment]
> i tried the dev build 673 released on oct 25th and it just makes it where it says incomp version of the game and wont let me join the server.

Reason is described here: https://github.com/dmulloy2/ProtocolLib/issues/2601

**Comment by Dymeth** [comment]
Try to use dev build of ProtocolLib v5.1.1 from here:
[1.8-1.19.4]: https://ci.dmulloy2.net/job/
[1.20.*+]: https://ci.dmulloy2.net/job/ProtocolLib/669/

Notice for 1.20 and 1.20.1 users:
Please, use 1.20.2 to confirm your issue with ProtocolLib.

Why not the last build for 1.20.2?
Last build (673) have critical issue at this moment; https://github.com/dmulloy2/ProtocolLib/issues/2601

If the problem persists, provide more information about your problem using this form:

- [ ] This issue is not solved in a development build

**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Version Info**
Provide your ProtocolLib install info with `/protocol dump` through pastebin.

**Additional context**
Add any other context about the problem here.
