### ISSUE TITLE
Players getting disconnected (clientbound/minecraft:update_attributes)

### ISSUE THREAD

**Issue by Nunchakin** [dmulloy2/ProtocolLib#3041]
- [x] This issue is not solved in a development build

**Describe the bug**
Players are (randomly?) getting disconnected from my survival server, idk whats causing it sometimes its after executing command sometimes its after just joining idk srry, the error:
https://pastebin.com/GY0YMqNc

**To Reproduce**
idk srry

**Expected behavior**
Players not getting disconnected

**Screenshots**
![image](https://github.com/dmulloy2/ProtocolLib/assets/151460657/08743aa4-564a-4904-bd43-c118bcc01ac2)

**Version Info**
https://pastebin.com/THGiQGSN

**Comment by Ingrim4** [comment]
This is an issue caused by another plugin and doesn't have anything to do with ProtocolLib as far as I can tell. The plugin sends a `ClientboundUpdateAttributesPacket` and while sending it changes values inside a field of the packet which causes the error. You would need to report this to the plugin author, problem is the error doesn't tell us what plugin sent the invalid packet, should be a plugin that modifies entity attributes (speed, health, attack_range, attack_speed, armor, etc.).

**Comment by Nunchakin** [comment]
Yeah fixed in ItemsAdder sorry
