### ISSUE TITLE
This plugin is not working with plugin remapper.

### ISSUE THREAD

**Issue by Satr9999** [dmulloy2/ProtocolLib#3092]
- [x] Please solve the problem 

**Plugin is not working with plugin remapper**
Plugin is not working with plugin remapper in papermc and I didn't know how to turn off plugin remapper. 

Please help guys

**Comment by Jeppa** [comment]
This plugin doen't need remapping (and tells Paper to not remap...)
Are you on latest build?

**Comment by KonPekora123** [comment]
> This plugin doen't need remapping (and tells Paper to not remap...) Are you on latest build?

Hello sir, The ProtocolLib wont work and will disable because the papee remapper will remap the plugin. I have the ItemsAdder plugin and because of the remapper the protocolLibs will disable protocolLib wont allow remapping. I will provide some screenshots if you want or I could be wrong, I'm willing to have a conversation with you privately if you want to teach me how paper works. I'm facing this problem for about 3 days now and ai cant find any solutions for it. Im also new to this kind of stuff
