### ISSUE TITLE
Hard Server crash when using MobHunting / ProtocolLib on PaperSpigot

### ISSUE THREAD

**Issue by Rocologo** [dmulloy2/ProtocolLib#324]
_Follow this template except for feature requests. Use pastebin when providing /protocol dump and any relevant errors._

Make sure you've done the following:
- [X] You're using the latest build for your server version
- [X] This isn't an issue caused by another plugin
- [X] You've checked for duplicate issues

Debug paste link:
https://paste.ee/p/YybGa

Description and relevant errors:
I'm using ProtocolLib to show a circle around a detected MobGrinding area. My code works fine on SpigotMC but I have a user who is using PaperSpigot, and his server make a hard crash (see the debug paste) (Here is his [ticket](https://github.com/Rocologo/MobHunting/issues/207))

My code is rather simple: https://github.com/Rocologo/MobHunting/blob/master/src/one/lindegaard/MobHunting/compatibility/ProtocolLibHelper.java#L102

I'm not sure if I do something wrong here or if ProtocolLib is not fully  PaperSpigot compatible?

**Comment by MiniDigger** [comment]
what you are seeing is not really a crash but a watchdog timeout. that means, that the server was lagging behind for 60 seconds and spigot watchdog decided to shut the server down. those thread dumps are hard to debug, because even tho protocollib and your plugin appear, that doesn't really mean that they caused it, the server could just be lagging in general. ask your user to provide a timings report to see whats running slow and causing the timeout.

**Comment by Rocologo** [comment]
Okay, thank you, i close this ticket again, until we get a timings report, and then i open it again or make a new one,
