### ISSUE TITLE
ProtocolLib not compatible with Java 23. (Works with Java 22)

### ISSUE THREAD

**Issue by andrewkm** [dmulloy2/ProtocolLib#3245]
ProtocolLib is not compatible with Java 23.
(Works fine with Java 22 which just ended security updates and released 23).

Paper 1.21.1 Build 96
ProtocolLib latest compiled against c9ee2f1
Bungeecord latest compiled against acb85e3

Removing ProtocolLib server loads and functions as it should.
Adding it back, client simply hangs on connecting to the server with error: https://i.imgur.com/uLDFE5S.png

**Comment by dmulloy2** [comment]
skimming through the changelog, it looks like they finally removed some of the officially unsupported reflection tricks we were using. will require some rework unfortunately

**Comment by Hiroyugane** [comment]
Can confirm. JDK23 not working. Using newest JDK 21.0.4+8-LTS-274 works fine

Non-working version tested with only ProtocolLib:
java version "23" 2024-09-17 64x (build 23+37-2369, mixed mode, sharing)

Error affects motd of server and ping not loading for players (instant "cant connect to server" instead of timeout) and, when trying to connect, aborts loading with an instant "disconnect" message. Tested with Paper #150 1.20.6 on localhost
