### ISSUE TITLE
Error with PacketPlayOutNamedEntitySpawn

### ISSUE THREAD

**Issue by Jumper251** [dmulloy2/ProtocolLib#367]
Debug paste link: https://pastebin.com/2iLUqtgZ
ProtocolLib Dump: https://pastebin.com/FzWELG2M

Description and relevant errors:
Packet entity spawning with WrapperPlayServerNamedEntitySpawn throws errors and does not work on Version 1.8.8

**Comment by MiniDigger** [comment]
> No field with type double exists in class PacketPlayOutNamedEntitySpawn

Check the nms class and wiki.vg to find out the right parameters for the packet

**Comment by Jumper251** [comment]
I am using the WrapperPlayServerNamedEntitySpawn with the recommended version (latest) from the Protocollib Spigot page.

**Comment by MiniDigger** [comment]
Your protocollib version doesn't matter, the version of the file from packet wrapper is wrong since it uses wrong parameters for the packet.

**Comment by Jumper251** [comment]
I use this wrapper: https://github.com/dmulloy2/PacketWrapper/blob/master/PacketWrapper/src/main/java/com/comphenix/packetwrapper/WrapperPlayServerNamedEntitySpawn.java

**Comment by MiniDigger** [comment]
as I said for the 3rd time now, you can't use latest protocol wrapper since you are using an outdated minecraft version. the protocol has changed, the coordinates were integers back then.
use this version of the wrapper https://github.com/dmulloy2/PacketWrapper/blob/cba7df1e77c7a71ab44f20948a5f768f0ccc3ffa/PacketWrapper/src/main/java/com/comphenix/packetwrapper/WrapperPlayServerNamedEntitySpawn.java

**Comment by dmulloy2** [comment]
You can't use new packet wrappers on old versions
