### ISSUE TITLE
Problem with any plugin of jump

### ISSUE THREAD

**Issue by TheSerialKInder** [dmulloy2/ProtocolLib#390]
Hi,
in my server when i press double space for the doublejump the player jump only in one direction, also with UltraCosmetics or another plugin to jump.

I don't know if it is ProtocolLib or not.

Sorry if it doesn't.

**Comment by MiniDigger** [comment]
this has nothing todo with protocollib, you should contact whatever jump plugin you want to use. they can let you jump in whatever direction they want.

**Comment by TheSerialKInder** [comment]
It is not true, I just removed the protocol and goes @MiniDigger

**Comment by ryantheleach** [comment]
@TheSerialKInder They are probably using ProtocolLib to determine when to jump.

Protocol Lib is a library used by other plugins, **even** if this ends up being a problem with protocol lib, report it to your jump plugins, let them investigate and determine whose fault it is.

**Then** they can create an issue with Protocol Lib, if it's found to be a problem with protocol lib.

If you have an error or something actionable, feel free to continue posting, otherwise no one here is going to be able to help.

**Comment by TheSerialKInder** [comment]
So i write an issue at UltraCosmetics?

**Comment by dmulloy2** [comment]
@TheSerialKInder yes
