### ISSUE TITLE
Project id 45564?

### ISSUE THREAD

**Issue by LogGits** [dmulloy2/ProtocolLib#467]
Keep getting this message in console?
```
[ProtocolLib] The updater could not find any files for the project id 45564
```
on the latest build 14th of April, using paperspigot.

**Comment by malonnnn** [comment]
I can confirm I just received this exact same error and so did this guy on spigot forums

https://www.spigotmc.org/threads/protocollib.36230/page-48#post-3003708

**Comment by MiniDigger** [comment]
This is thrown by the bukkitdev update check. Normally protocollib should detect that you are using spigot and use the spigot updater, but since you are using paper that check doesn't work.
I will write up a pr to fix that check later, maybe @dmulloy2 can check why the bukkit updater broke (I assume this is caused by some Backend Change at curse)

Anyways, the error doesn't really have to concern you, the plugin will work as intended, it will just not notify you about new updates automatically.

**Comment by NullCase** [comment]
I'm the other guy ^^. 

Fwiw, I am also using a quite recent version of Paper.
