### ISSUE TITLE
ProtocolLib Refusing to allow server boot

### ISSUE THREAD

**Issue by 1979ProfessionalWordDocumentPaster** [dmulloy2/ProtocolLib#473]
Crash-Log:
https://hastebin.com/iretukehub.swift

Server boots all plugins fine, tries to boot PL and it freezes for a moment and crashes. Have reinstalled server files and PL to assure this crash was not an error on my behalf.

**Comment by dmulloy2** [comment]
Looks like this was fixed by Spigot in 2016: https://hub.spigotmc.org/stash/projects/SPIGOT/repos/bukkit/commits/55941791e10363558be365954215217eb6c6734f#src/main/java/org/bukkit/plugin/java/JavaPluginLoader.java

Not really sure what the fix for 1.8 is though. Maybe disable the background compiler?

**Comment by dmulloy2** [comment]
You can disable the background compiler here: https://github.com/dmulloy2/ProtocolLib/blob/master/modules/ProtocolLib/src/main/resources/config.yml#L13
