### ISSUE TITLE
 java.lang.IllegalArgumentException: Unable to find a field null with the type io.netty.channel.Channel in net.minecraft.server.v1_7_R4.NetworkManager

### ISSUE THREAD

**Issue by CDGamesYT** [dmulloy2/ProtocolLib#619]
_Follow this template except for feature requests. Use pastebin when providing /protocol dump and any relevant errors._

Make sure you've done the following:
- [x] You're using the latest build for your server version
- [ ] This isn't an issue caused by another plugin
- [x] You've checked for duplicate issues
- [x] You didn't use `/reload`

Debug paste link: https://hatebin.com/hrgstgqlko

Description and relevant errors:

**Comment by TheDGOfficial** [comment]
You have to use v3.6.5 for Minecraft 1.7.10:
https://github.com/dmulloy2/ProtocolLib/releases/download/v3.6.5/ProtocolLib.jar

You can also use v3.7.0 which contains critical fixes, but for my testing it does not work with NoCheatPlus and gives strange errors.

I think it is not possible to support 1.7.10 in recent versions of ProtocolLib due to changes in 1.8. In 1.8, the Netty is moved from net.minecraft.util.io.netty to io.netty. So you get this error.
