### ISSUE TITLE
server crash

### ISSUE THREAD

**Issue by slvlr** [dmulloy2/ProtocolLib#640]
_Follow this template except for feature requests. Use pastebin when providing /protocol dump and any relevant errors._

Make sure you've done the following:
- [x] You're using the latest build for your server version
- [x] This isn't an issue caused by another plugin
- [x] You've checked for duplicate issues
- [x] You didn't use `/reload`

Debug paste link: https://pastebin.com/9HCa4ex8

Description and relevant errors: Server crashed, this was in the logs (spammed), has protocol lib errors in it?

**Comment by slvlr** [comment]
It appears that this crash would occur when entering a certain chunk. The crash only happened when Libs disguises is installed, when removed the chunk no longer causes the crashes?

**Comment by dmulloy2** [comment]
ProtocolLib _is_ in the stack trace, but nothing in there indicates that it's the _cause_

**Comment by MiniDigger** [comment]
libs disguises is validating entities and thus loading chunks, making your server not be able to keep up. this is not caused by protocollib. report this is lib. 
I know that md made changes to how isValid works or smth, so that is something lib should look into. A isValid check shouldn't cause a chunk load, bukkit is drunk.
