### ISSUE TITLE
Wild command isn't working anymore

### ISSUE THREAD

**Issue by RevengeOfJedi** [dmulloy2/ProtocolLib#737]
Hi, I am using your plugin in my server and also using WildernessTp plugin which teleports player to random location in a world. So I was using Protocollib 4.3 for my spigot 1.12.2 minecraft server. I was able to use /wild command (wildernessTp plugin) but somehow suddenly i am not able to whenever i try i am getting some errors i contact developers in their discord . They told me ProtocolLib might be causing this error so  i am try to figure out with you any help would be appreciated. Thanks in advance. 
I use /wild command at 757 so you can see the error there
here is my console log:  https://pastebin.pl/view/a9f82ecf
my server version: spigot 1.12.2

**Comment by RevengeOfJedi** [comment]
Also after issue occured i update Protocollib to 4.4 but still gettin this error

**Comment by MiniDigger** [comment]
this has nothing to do with protocollib. the plugin is utterly stupid and runs into a stackoverflow because it tried and tried and tried to find a random location thousands of times. the developer needs to put a saveguard there. 

may I suggest a properly designed plugin instead?
https://www.spigotmc.org/resources/wilderness-tp.22853/

**Comment by MiniDigger** [comment]
this is actually caused by a recent update, looks like the author didnt bother to test it at all, the logic here is clearly flawed:
https://github.com/Qballl/WildernessTp/blob/1e24cdfb1a9e77e1e0144da3666535d35148b432/src/main/java/me/Qball/Wild/Utils/GetRandomLocation.java#L126
was commited 3 days ago

**Comment by dmulloy2** [comment]
Yeah this has nothing to do with ProtocolLib. Not sure how he saw that giant stack overflow from his plugin and think it was PL’s fault.
