### ISSUE TITLE
Get a faster maven repository

### ISSUE THREAD

**Issue by Techcable** [dmulloy2/ProtocolLib#78]
The protcollib maven repository is the bottleneck of my builds.
According to [this](http://tools.pingdom.com/fpt/#!/cLO2Cg/http://ci.shadowvolt.com/plugin/repository/everything/) the maven repository takes **10 seconds** to load, and is slower than 87% of websites. I suggest getting a dedicated maven repository like nexus to speed up builds. If it is absolutely necessary i can host your repo.

Do you use cloudfare? If not i recommend getting that for a CDN and automatic cache.

**Comment by dmulloy2** [comment]
The maven repository is a Jenkins plugin, which was originally just for my smaller projects.  I didn't intend on using it for a large, widely used plugin like ProtocolLib, but it's what I had at the time and it worked well enough.  I'm not willing upgrade and pay any more than I do because a free plugin takes an extra 10 seconds to load.  It doesn't make sense for me because a) I don't care if my builds take an extra 10 seconds to build and b) I don't get paid to maintain ProtocolLib.

With that said, if 10 seconds (a minuscule 1/8,640th of your day) really means that much to you, according to the speed test site you linked, [this part](http://ci.shadowvolt.com/plugin/repository/project/ProtocolLib/LastSuccessful/repository/) of the repository is [faster than 96% of websites](http://tools.pingdom.com/fpt/#!/cLxEZ3/http://ci.shadowvolt.com/plugin/repository/project/ProtocolLib/LastSuccessful/repository/).
