### ISSUE TITLE
Connection reset error

### ISSUE THREAD

**Issue by LoXR** [dmulloy2/ProtocolLib#861]
**Describe the bug**
Getting this error everytime a player leaves on my 1.13.2 Hub: https://mcpaste.io/4aeb52ebdd72b402

**To Reproduce**
1. Join
2. Join a server or disconnect
3. See error in console

**Expected behavior**
I suppose for it to not spam the error, and hopefully this error isnt causing the hubs to crash.

**Screenshots**
none.

**Version Info**
https://pastebin.com/bgRRmdKB

**Additional context**
none.

**Comment by xRebellion** [comment]
I got a similar error that happens whenever a player joins and then disconnects the server before even entering, and it spams the console horribly, though apart from the spam in doesn't seem to cause any issue otherwise.

Here's a part of the error (it's just the same error repeating a ton of times)
https://pastebin.com/x4FBmW0d
And here's my dump file
https://pastebin.com/spv7uEpK

It's also maybe worth noting that it doesn't fire the PlayerQuitEvent, since no leave messages are sent when the player disconnects in such a way.

**Comment by LoXR** [comment]
Yep have no clue how to fix it, gone back many versions, tried all different Jenkins builds, even the official spigot releases. Still pops up.

**Comment by LoXR** [comment]
Was possibly due to ViaVersion, since i've realised its gone now since the latest DEV updates.
